Repository NeuraLegion/broken_crystals, pull requests merged in 2020-05, with the labels that each got.

#5 Basic XSS
  README.md
  shard.yml
  src/broken_crystals.cr
  src/views/main.ecr
  src/views/reflected_xss.ecr
Labels: enhancement

#9 #3 feat/database manager
  .env.example
  .gitignore
  shard.lock
  shard.yml
  src/db/db.md
  src/db/migration.cr
  src/db/migration_down.cr
  src/db/migration_up.cr
  src/db/migrations/db_config.cr
  src/db/migrations/users.cr
  src/repositories/db_wrapper.cr
  src/repositories/mutable_repository.cr
  src/repositories/read_repository.cr
Labels: enhancement

#10 More XSS vulnerabilities
  src/broken_crystals.cr
  src/views/main.ecr
  src/views/reflected_xss.ecr
Labels: enhancement

#11 LFI vulnerabilities
  public/LFI/crystals_1.jpg
  src/broken_crystals.cr
  src/views/main.ecr
Labels: enhancement

#12 feat(user): add user auth
  public/css/login.css
  src/broken_crystals.cr
  src/controllers/user_controller.cr
  src/repositories/db_wrapper.cr
  src/repositories/mutable_repository.cr
  src/repositories/read_repository.cr
  src/views/users/dashboard.ecr
  src/views/users/login.ecr
  src/views/users/register.ecr
Labels: enhancement

#13 New vulnerability: pXSS
  src/broken_crystals.cr
  src/db/migration_down.cr
  src/db/migration_up.cr
  src/db/migrations/comment_pxss.cr
  src/models/comment.cr
  src/views/error.ecr
  src/views/main.ecr
  src/views/pxss_one.ecr
Labels: enhancement

#14 More OSI
  src/broken_crystals.cr
  src/views/main.ecr
Labels: enhancement

#15 added CSRF to broken_crystals
  src/broken_crystals.cr
  src/views/csrf.ecr
  src/views/csrf_rss.ecr
  src/views/main.ecr
Labels: enhancement

#16 Refactor/better repos less safe repos
  .gitignore
  README.md
  cli.cr
  public/css/main.css
  shard.lock
  shard.yml
  src/broken_crystals.cr
  src/controllers/csrf_controller.cr
  src/controllers/lfi_controller.cr
  src/controllers/uptime_controller.cr
  src/controllers/xss_controller.cr
  src/db/migrations/comment_pxss.cr
  src/db/migrations/db_config.cr
  src/models/comment.cr
  src/repositories/comment_repository.cr
  src/repositories/read_repository.cr
  src/views/main.ecr
Labels: enhancement

#18 feat(user): introduce session
  .env.example
  cli.cr
  shard.lock
  shard.yml
  src/broken_crystals.cr
  src/controllers/user_controller.cr
  src/models/user_session.cr
Labels: enhancement, good first issue

#20 moddified README.md and shard.yml
  README.md
  shard.yml
Labels: documentation

#24 feat: add config
  .env.example
  cli.cr
  shard.lock
  shard.yml
  src/broken_crystals.cr
  src/config.cr
  src/db/migration.cr
  src/repositories/db_wrapper.cr
Labels: enhancement

#26 sign in btn fix
  public/assets/css/style.css
Labels: enhancement

#28 Crecto ORM Integration and some fixes
  db/migrations/20200514153213_products.sql
  db/migrations/20200515084202_photos.sql
  db/repo.cr
  shard.lock
  shard.yml
  src/controllers/home_controller.cr
  src/controllers/shop_controller.cr
  src/models.cr
  src/views/csrf.ecr
  src/views/pxss_one.ecr
Labels: enhancement

#31 DB improvement & seeder, ORM fixes, pXSS vuln implemented
  README.md
  db/micrate.cr
  db/migrations/20200514153213_products.sql
  db/migrations/20200519115455_categories.sql
  db/migrations/20200519132039_products.sql
  db/migrations/20200519132147_photos.sql
  db/migrations/20200521112657_testimonials.sql
  db/seed.cr
  src/controllers/home_controller.cr
  src/models.cr
  src/views/main.ecr
Labels: enhancement
